# Generated by Django 4.1.1 on 2022-10-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_artists_snakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150)),
                ('length', models.IntegerField(default=0)),
                ('snakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snakes', to='main_app.snakes')),
            ],
        ),
    ]
