# Generated by Django 4.1.1 on 2022-10-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_snakes_snakedata_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snakedata',
            old_name='region',
            new_name='habitats',
        ),
    ]
