# Generated by Django 4.1.1 on 2022-10-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_region_snakedata_habitats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('food', models.CharField(max_length=150)),
                ('data', models.ManyToManyField(to='main_app.snakedata')),
            ],
        ),
    ]
