# Generated by Django 4.1.1 on 2022-10-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_snakelist_snakelists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snakelists',
            old_name='data',
            new_name='list',
        ),
    ]
