# Generated by Django 4.1.1 on 2022-10-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_data_snakelists_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakes',
            name='img',
            field=models.CharField(max_length=1000),
        ),
    ]
