# Generated by Django 4.1.1 on 2022-10-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_snakes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakes',
            name='species_info',
            field=models.TextField(max_length=1500),
        ),
    ]
